== Protecion Profile Module for Email Clients

== This version of the Module is deprecated. From now on use the email-client repo.

[cols="1,1,1,1,1,1,1,1"]
|===
8+|emailclient 
| https://github.com/commoncriteria/emailclient/tree/master[master] 
a| https://commoncriteria.github.io/emailclient/master/emailclient-release.html[📄]
a|[link=https://github.com/commoncriteria/emailclient/blob/gh-pages/master/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/emailclient/gh-pages/master/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/emailclient/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/emailclient/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/emailclient/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/emailclient/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/emailclient/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/emailclient/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/emailclient/gh-pages/master/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/emailclient/blob/gh-pages/master/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/emailclient/gh-pages/master/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/emailclient/blob/gh-pages/master/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/emailclient/gh-pages/master/pdf_count.svg[PDF Count]
|===

https://github.com/commoncriteria/emailclient/issues[image:https://img.shields.io/github/issues/commoncriteria/emailclient.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

This repository hosts the draft version of the Protection Profile Module for Email Clients based on the 
[Essential Security Requirements (ESR)](https://commoncriteria.github.io/pp/emailclient/emailclient-esr.html) for this technology class of 
products. This repository is used to facilitate collaboration and development on the draft document. 
See the [release](#Release-Version) section if you are looking for the officially released version for evaluations. 
A list of products that have passed evaluation against this Protection Profile can be found [here](https://www.niap-ccevs.org/Profile/Info.cfm?id=377).

## Draft Version

* [Protection Profile Module for Email Clients](https://commoncriteria.github.io/pp/emailclient/emailclient-release.html) (html)
* [Protection Profile Module for Email Clients](https://commoncriteria.github.io/pp/emailclient/emailclient-release.pdf) (pdf)

## Release Version
* [Protection Profile Module for Email Clients](https://www.niap-ccevs.org/Profile/Info.cfm?id=377)

## Contributing

If you are interested in contributing directly to future versions the this Protection Profile, please consider joining the NIAP technical community.
* [How to join the NIAP Technical Community (Mailing list and updates)](https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm)

## Feedback

Questions, comments, and fixes can be submitted to the [repository issue tracker](https://github.com/commoncriteria/emailclient/issues)

## Quickstart
To clone this project along with its _transforms_ submodule run:

````
  git clone --recursive git@github.com:commoncriteria/emailclient.git
````
To pull updates from the upstream _transforms_ submodule and commit them run:
````
 git submodule update --remote transforms
 git add transforms
 git commit
````

### Development Info
[Help working with Transforms Submodule](https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule)

## Repository Content
* input - Contains the 'meat' of the project. It's the input content (in XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a repository for resources shared amongst many Common Criteria projects.

## Links 
* [National Information Assurance Partnership (NIAP)](https://www.niap-ccevs.org/)
* [Common Criteria Portal](https://www.commoncriteriaportal.org/)

## License
See [License](./LICENSE)
